### ISSUE TITLE
Screen Black, no Video only on Android

### ISSUE THREAD

**Issue by BrunoC96** [media-kit/media-kit-android-helper#5]
Hi I'm trying to use the media_kit for see a video stream but, the screen is full black, and I have this error message:

Invalid argument(s): Failed to load dynamic library 'libavcodec.so': dlopen failed: library "libavcodec.so" not found
I/flutter (23344): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
I/flutter (23344): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
I/flutter (23344): #2      AndroidHelper.ensureInitialized (package:media_kit/src/utils/android_helper.dart:23:43)
I/flutter (23344): #3      libmpvEnsureInitialized (package:media_kit/src/player/libmpv/player/real.dart:40:17)
I/flutter (23344): #4      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:39:7)

i have tested the video on Ios and works just fine, and the problem is only here.

**Comment by alexmercerind** [comment]
1. Upgrade all dependencies as specified in "Installation" section.
2. Provide your `pubspec.yaml`.

**Comment by BrunoC96** [comment]
ac_connectivity: ^0.1.0
  ansicolor: ^2.0.1
  auto_orientation: ^2.3.1
  badges: ^3.1.1
  camera: ^0.10.5+2
  cloud_firestore: ^4.7.1
  collection: ^1.17.1
  crypto: ^3.0.3
  dart_reed_solomon_nullsafety: ^0.2.0
  device_info_plus: ^8.2.2
  dio: ^5.1.1
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  encrypt: ^5.0.1
  equatable: ^2.0.5
  expandable_tree_menu: ^0.1.0-dev.5
  file_picker: ^5.2.10
  fire_tv_listener: ^0.0.6
  firebase_auth: ^4.5.0
  firebase_core: ^2.13.0
  firebase_dart: ^1.0.9
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_hls_parser: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_meedu_media_kit: ^4.2.12
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  google_fonts: ^4.0.4
  http: ^0.13.6
  icons_launcher: ^2.1.0
  intl: ^0.18.0
  js: ^0.6.5
  json_annotation: ^4.8.1
  jumping_dot: ^0.0.6
  local_value: ^1.2.0
  logger: ^2.0.1
  media_kit: 1.0.2
  media_kit_video: ^1.0.2
  path_provider: ^2.0.15
  responsive_builder: ^0.7.0
  scrollable_positioned_list: ^0.3.8
  shelf: ^1.4.1
  shimmer: ^3.0.0
  shrink_sidemenu: ^2.0.0+2-null-safety
  sleek_circular_slider: ^2.0.1
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  wakelock: ^0.6.2
  win32: ^3.1.4

**Comment by alexmercerind** [comment]
I'm going to delete issue from this repository to maintain hygiene, you can keep personal record on your e-mail.

The help is provided above. You'll obviously get error if you haven't added dependency.
